- data-egress.tf
Signed-off-by: danhill <danhill@digital.uc.dwp.gov.uk>
> remove the count conditional from the CloudWatch log group

- outputs.tf
> outputting data egress server securiyt group id

- cluster_ecs.tf
- cluster_iam.tf
- data-egress_iam.tf
- files/data_egress_cluster_userdata.tpl
- terraform.tf.j2
Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>
> added GUID to ec2 instances launched by this cluster

- cluster_ecs.tf
- cluster_iam.tf
- data-egress_iam.tf
- files/data_egress_cluster_userdata.tpl
Reverts dwp/dataworks-aws-data-egress#13
> Revert "added GUID to ec2 instances launched by this cluster"

- cluster_ecs.tf
- cluster_iam.tf
- data-egress_iam.tf
- files/data_egress_cluster_userdata.tpl
Reverts dwp/dataworks-aws-data-egress#14
> Revert "Revert "added GUID to ec2 instances launched by this cluster""

- data-egress_ecs.tf
Reverts dwp/dataworks-aws-data-egress#16
> Revert "Dw 5433"

- data-egress_ecs.tf
Reverts dwp/dataworks-aws-data-egress#17
> Revert "Revert "Dw 5433""

- data-egress_ecs.tf
Reverts dwp/dataworks-aws-data-egress#18
> Revert "Revert "Revert "Dw 5433"""

- cluster_ecs.tf
- terraform.tf.j2
- variables.tf
Use GP3 which is much cheaper and shrink the size except for prod
> Use GP3 which is much cheaper and shrink the size except for prod

- ci/jobs/development.yml
- ci/jobs/qa.yml
- ci/meta.yml
- ci/resources.yml
- cluster_ecs.tf
Fix data egress pipeline and switch to new e2e repo
> Fix data egress pipeline and switch to new e2e repo

- locals.tf
- outputs.tf
- sft-agent_ecs_task.tf
Signed-off-by: Connor Avery <ConnorAvery@digital.uc.dwp.gov.uk>
> Desired capacity for SFT Agent, also output as TF output

- data-egress.tf
- data-egress_ecs_task.tf
- data-egress_iam.tf
- outputs.tf
Remove sqs queue and use the output of common
> Remote queue

- sft-agent_sg.tf
> sending to sdx f1 cidr block

- data-egress_ecs_task.tf
- locals.tf
- sft-agent_iam.tf
- variables.tf
> sft retrieving certs

- variables.tf
> using sft agent 8

- variables.tf
> latest sft agent image

- sft-agent_iam.tf
> allowing sft agent to export cert

- data-egress_ecs_task.tf
- reserved_container_definition.tpl
> make sft non essential while testing

- data-egress_ecs_task.tf
- variables.tf
> added proxy settings for sft agent

- data-egress_ecs_task.tf
- locals.tf
- variables.tf
> using cert exporter in all evns

- sft-agent_sg.tf
> better count

- data-egress_ecs_task.tf
- locals.tf
- variables.tf
> adding testing

- locals.tf
- variables.tf
> corrected image versions, testing in qa too

- ci/jobs/cycle-containers/cycle_egress.yml
- variables.tf
> latest sft agent

- data-egress_ecs_task.tf
- locals.tf
- variables.tf
> latest agent

- sft_config/agent-config.tpl
- variables.tf
> updated agent config with ssl config, latest sft agent image

- sft_config/agent-config.tpl
> updated placeholder text, corrceted key store type

- sft_config/agent-config.tpl
> correct tstore password string

- variables.tf
> sft image 23

- locals.tf
- sft-agent_s3_config.tf
- sft_config/agent-config-with-tls.tpl
- sft_config/agent-config.tpl
- variables.tf
> different agent config for prod

- locals.tf
- sft_config/agent-config-with-tls.tpl
- variables.tf
> removed some ssl congig. removed sdk certs

- variables.tf
> latest sft

- sft_config/agent-application-config-prod-test.tpl
- variables.tf
> removed threading from sft config

- locals.tf
- variables.tf
> readded sdx crets

- variables.tf
> sft agent with same key passwords

- sft_config/agent-application-config-prod-test.tpl
> changed route to ifts testroute

- ci/groups.yml
- ci/jobs/development.yml
- ci/jobs/integration.yml
- ci/jobs/preproduction.yml
- ci/jobs/production.yml
- ci/jobs/qa.yml
- ci/meta.yml
- sft_config/agent-application-config-prod-test.tpl
> added cycle container jobs and updated route name

- sft_config/agent-application-config-prod-test.tpl
> routes tabbed in

- ci/jobs/qa.yml
- variables.tf
> latest egress image

- sft-agent_s3_config.tf
> Remove tf11 syntax

- data-egress.tf
- locals.tf
- terraform.tf.j2
dynamoDB items updated for HTME for 68 collections
> dynamoDB items updated for HTME for 68 collections

- data-egress_ecs_task.tf
> exposing the port jmx exporter is running on

- locals.tf
> changed production to use the same config as dev for now

- data-egress_ecs_task.tf
- data-egress_iam.tf
Added policy to grant "GetObject" "GetObjectLocation" "ListBucket" for compaction bucket to Data egress
> Added compaction bucket access policy

- data-egress.tf
Range keys on manifest files updated to resolve the conflicting conditional operation issue
> Range keys on manifest files updated to resolve the conflicting conditional operation

- data-egress.tf
- locals.tf
- terraform.tf.j2
> Add RIS DDB items

- data-egress.tf
> Cope with not set collections

- data-egress.tf
> corrected path in source prefix

- data-egress.tf
> correct ris prefix

- data-egress.tf
DW-6997 change DWH source prefix
> DW-6997 change DWH source prefix

- data-egress.tf
DW-6997 set decrypt to true for DWH SFT
> DW-6997 set decrypt to true for DWH SFT

- data-egress.tf
- variables.tf
> pdm jsons dynamo table

- data-egress_ecs_task.tf
- variables.tf
> increase memory and cpu

- data-egress.tf
- data-egress_ecs_task.tf
- variables.tf
> adjust memory hard limits

- data-egress_ecs_task.tf
- variables.tf
> pin sft version per env and bump in lower envs

- data-egress_ecs_task.tf
- sft_config/agent-application-config.tpl
- variables.tf
> remove renaming, reduce threads to 3, bump version of sft in all envs

- README.md
> add link to common wiki page

- outputs.tf
Reverts dwp/dataworks-aws-data-egress#213
> Revert "Kms key output "

- data-egress.tf
- data-egress_iam.tf
Added a new table in dynamo DB for Data Egress to egress data to published-output bucket.
Added IAM policy for data egress to move data from preprocess_csv folder to published-output bucket.
> Byuc 1949 s3 permissions ml

- ci/meta.yml
- cluster_ecs.tf
- files/data_egress_cluster_userdata.tpl
- terraform.tfvars.j2
- variables.tf
- maps correct device and resizes lvm
- unpins default ami from tf code
- renames ami variables
> hcs ami for data-egress infra

- sft_config/agent-application-config.tpl
Changes scheduled for 20th April at 1pm
DandA migrating at their end so we need to update the routes at our end.
> chore: Scheduled DandA route changes
